services:
  frontend:
    build: ./frontend
    container_name: frontend-ui
    ports:
      - "8080:80"
    depends_on:
      - integration-service

  integration-service:
    build: ./integration_service
    container_name: integration-service
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Redis__Configuration: redis:6379
      Services__ObjectService: http://object-service:5001
      Services__DepreciationService: http://depreciation-service:5002
      Services__DisposalService: http://disposal-service:3000
    depends_on:
      - object-service
      - depreciation-service
      - disposal-service
      - postgres
      - redis

  object-service:
    build: ./object_service
    container_name: object-service
    ports:
      - "5001:5001"

  depreciation-service:
    build: ./depreciation_service
    container_name: depreciation-service
    ports:
      - "5002:5002"

  disposal-service:
    build: ./disposal_service
    container_name: disposal-service
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fixed_assets
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
